import { Region } from '../../../types';

export const NATIONAL_TEAMS_EUROPE = [
  { name: "Albania", continent: "Europe", tier: 4, colors: ["#E41E20","#000000","#E41E20"], stadium: "Air Albania Stadium", capacity: 22500, reputation: 9, region: Region.ALBANIA },
  { name: "Andora", continent: "Europe", tier: 5, colors: ["#0032A0","#FEDD00","#D52B1E"], stadium: "Estadi Nacional", capacity: 3306, reputation: 2, region: Region.IBERIA },
  { name: "Armenia", continent: "Europe", tier: 4, colors: ["#D90012","#0033A0","#F2A800"], stadium: "Republican Stadium", capacity: 14200, reputation: 7, region: Region.ARMENIA },
  { name: "Austria", continent: "Europe", tier: 2, colors: ["#ED2939","#FFFFFF","#ED2939"], stadium: "Ernst-Happel-Stadion", capacity: 50708, reputation: 14, region: Region.GERMANY },
  { name: "Azerbejdżan", continent: "Europe", tier: 4, colors: ["#00B9E4","#ED2939","#3F9C35"], stadium: "Baku Olympic Stadium", capacity: 69870, reputation: 6, region: Region.AZERBAIJANI },
  { name: "Belgia", continent: "Europe", tier: 1, colors: ["#000000","#FFD100","#EF3340"], stadium: "King Baudouin Stadium", capacity: 50093, reputation: 17, region: Region.BENELUX },
  { name: "Białoruś", continent: "Europe", tier: 4, colors: ["#D22730","#00AF66","#FFFFFF"], stadium: "Dinamo Stadium", capacity: 22346, reputation: 6, region: Region.EX_USSR },
  { name: "Bośnia i Hercegowina", continent: "Europe", tier: 4, colors: ["#002395","#FECB00","#002395"], stadium: "Bilino Polje", capacity: 15292, reputation: 9, region: Region.BALKANS },
  { name: "Bułgaria", continent: "Europe", tier: 4, colors: ["#FFFFFF","#00966E","#D62612"], stadium: "Vasil Levski", capacity: 43230, reputation: 8, region: Region.BALKANS },
  { name: "Chorwacja", continent: "Europe", tier: 2, colors: ["#FF0000","#FFFFFF","#0000FF"], stadium: "Maksimir", capacity: 35000, reputation: 17, region: Region.BALKANS },
  { name: "Cypr", continent: "Europe", tier: 4, colors: ["#FFFFFF","#D57800","#FFFFFF"], stadium: "GSP Stadium", capacity: 22859, reputation: 6, region: Region.GREEK },
  { name: "Czarnogóra", continent: "Europe", tier: 4, colors: ["#C40308","#FFD700","#C40308"], stadium: "Pod Goricom", capacity: 17000, reputation: 7, region: Region.BALKANS },
  { name: "Czechy", continent: "Europe", tier: 2, colors: ["#11457E","#FFFFFF","#D7141A"], stadium: "Eden Arena", capacity: 20800, reputation: 13, region: Region.CZ_SK },
  { name: "Dania", continent: "Europe", tier: 2, colors: ["#C60C30","#FFFFFF","#C60C30"], stadium: "Parken", capacity: 38065, reputation: 15, region: Region.SCANDINAVIA },
  { name: "Estonia", continent: "Europe", tier: 5, colors: ["#4891D9","#000000","#FFFFFF"], stadium: "A. Le Coq Arena", capacity: 14336, reputation: 5, region: Region.BALTIC },
  { name: "Finlandia", continent: "Europe", tier: 3, colors: ["#FFFFFF","#003580","#FFFFFF"], stadium: "Olympic Stadium Helsinki", capacity: 36300, reputation: 9, region: Region.FINLAND },
  { name: "Francja", continent: "Europe", tier: 1, colors: ["#0055A4","#FFFFFF","#EF4135"], stadium: "Stade de France", capacity: 80000, reputation: 20, region: Region.FRANCE },
  { name: "Gibraltar", continent: "Europe", tier: 5, colors: ["#D40000","#FFFFFF","#D40000"], stadium: "Victoria Stadium", capacity: 5000, reputation: 2, region: Region.IBERIA },
  { name: "Grecja", continent: "Europe", tier: 2, colors: ["#0D5EAF","#FFFFFF","#0D5EAF"], stadium: "Olympic Stadium Athens", capacity: 69618, reputation: 12, region: Region.GREEK },
  { name: "Gruzja", continent: "Europe", tier: 4, colors: ["#FFFFFF","#E41E20","#FFFFFF"], stadium: "Boris Paichadze", capacity: 54949, reputation: 9, region: Region.GEORGIA },
  { name: "Hiszpania", continent: "Europe", tier: 1, colors: ["#AA151B","#F1BF00","#AA151B"], stadium: "Santiago Bernabéu", capacity: 81044, reputation: 20, region: Region.SPAIN },
  { name: "Holandia", continent: "Europe", tier: 1, colors: ["#FF4F00","#FFFFFF","#0000FF"], stadium: "Johan Cruijff Arena", capacity: 55500, reputation: 18, region: Region.BENELUX },
  { name: "Irlandia", continent: "Europe", tier: 3, colors: ["#169B62","#FFFFFF","#FF883E"], stadium: "Aviva Stadium", capacity: 51711, reputation: 11, region: Region.ENGLAND },
  { name: "Islandia", continent: "Europe", tier: 3, colors: ["#02529C","#FFFFFF","#DC1E35"], stadium: "Laugardalsvöllur", capacity: 15000, reputation: 9, region: Region.SCANDINAVIA },
  { name: "Izrael", continent: "Europe", tier: 3, colors: ["#0038B8","#FFFFFF","#0038B8"], stadium: "Sammy Ofer Stadium", capacity: 30858, reputation: 12, region: Region.ISRAELI },
  { name: "Kazachstan", continent: "Europe", tier: 4, colors: ["#00AFCA","#FEC50C","#00AFCA"], stadium: "Astana Arena", capacity: 30000, reputation: 7, region: Region.KAZAKH },
  { name: "Kosovo", continent: "Europe", tier: 4, colors: ["#244AA5","#D0A650","#244AA5"], stadium: "Fadil Vokrri Stadium", capacity: 13800, reputation: 8, region: Region.ALBANIA },
  { name: "Liechtenstein", continent: "Europe", tier: 5, colors: ["#002B7F","#CE1126","#FFD100"], stadium: "Rheinpark Stadion", capacity: 7838, reputation: 2, region: Region.GERMANY },
  { name: "Litwa", continent: "Europe", tier: 5, colors: ["#FDB913","#006A44","#C1272D"], stadium: "LFF Stadium", capacity: 5067, reputation: 5, region: Region.BALTIC },
  { name: "Luksemburg", continent: "Europe", tier: 5, colors: ["#00A3E0","#FFFFFF","#EF3340"], stadium: "Stade de Luxembourg", capacity: 9385, reputation: 4, region: Region.BENELUX },
  { name: "Łotwa", continent: "Europe", tier: 5, colors: ["#9E3039","#FFFFFF","#9E3039"], stadium: "Daugava Stadium", capacity: 10000, reputation: 5, region: Region.BALTIC },
  { name: "Macedonia Północna", continent: "Europe", tier: 3, colors: ["#D20000","#FFD700","#D20000"], stadium: "Toše Proeski Arena", capacity: 33500, reputation: 8, region: Region.BALKANS },
  { name: "Malta", continent: "Europe", tier: 5, colors: ["#FFFFFF","#CF142B","#FFFFFF"], stadium: "Ta' Qali", capacity: 17797, reputation: 3, region: Region.MALTESE },
  { name: "Mołdawia", continent: "Europe", tier: 4, colors: ["#0033A0","#FFD100","#CE1126"], stadium: "Zimbru", capacity: 10400, reputation: 6, region: Region.EX_USSR },
  { name: "Niemcy", continent: "Europe", tier: 1, colors: ["#000000","#DD0000","#FFCE00"], stadium: "Olympiastadion Berlin", capacity: 74475, reputation: 20, region: Region.GERMANY },
  { name: "Norwegia", continent: "Europe", tier: 3, colors: ["#BA0C2F","#FFFFFF","#00205B"], stadium: "Ullevaal", capacity: 28000, reputation: 11, region: Region.SCANDINAVIA },
  { name: "Polska", continent: "Europe", tier: 2, colors: ["#FFFFFF","#DC143C","#FFFFFF"], stadium: "Stadion Narodowy", capacity: 58580, reputation: 14, region: Region.POLAND },
  { name: "Portugalia", continent: "Europe", tier: 1, colors: ["#006600","#FF0000","#006600"], stadium: "Estádio da Luz", capacity: 64642, reputation: 18, region: Region.IBERIA },
  { name: "Rosja", continent: "Europe", tier: 2, colors: ["#FFFFFF","#0039A6","#D52B1E"], stadium: "Luzhniki Stadium", capacity: 81000, reputation: 13, region: Region.EX_USSR },
  { name: "Rumunia", continent: "Europe", tier: 3, colors: ["#002B7F","#FCD116","#CE1126"], stadium: "Arena Națională", capacity: 55634, reputation: 12, region: Region.ROMANIA },
  { name: "San Marino", continent: "Europe", tier: 5, colors: ["#5EB6E4","#FFFFFF","#5EB6E4"], stadium: "San Marino Stadium", capacity: 6664, reputation: 1, region: Region.ITALY },
  { name: "Serbia", continent: "Europe", tier: 2, colors: ["#C6363C","#0C4076","#FFFFFF"], stadium: "Rajko Mitić", capacity: 53530, reputation: 14, region: Region.BALKANS },
  { name: "Słowacja", continent: "Europe", tier: 3, colors: ["#FFFFFF","#0B4EA2","#EF3340"], stadium: "Tehelné pole", capacity: 22500, reputation: 10, region: Region.CZ_SK },
  { name: "Słowenia", continent: "Europe", tier: 3, colors: ["#FFFFFF","#005DA4","#ED1C24"], stadium: "Stožice", capacity: 16038, reputation: 10, region: Region.BALKANS },
  { name: "Szkocja", continent: "Europe", tier: 2, colors: ["#0065BD","#FFFFFF","#0065BD"], stadium: "Hampden Park", capacity: 51866, reputation: 12, region: Region.ENGLAND },
  { name: "Szwajcaria", continent: "Europe", tier: 2, colors: ["#FF0000","#FFFFFF","#FF0000"], stadium: "St. Jakob-Park", capacity: 38512, reputation: 15, region: Region.GERMANY },
  { name: "Szwecja", continent: "Europe", tier: 2, colors: ["#006AA7","#FECC00","#006AA7"], stadium: "Friends Arena", capacity: 50000, reputation: 15, region: Region.SCANDINAVIA },
  { name: "Turcja", continent: "Europe", tier: 2, colors: ["#E30A17","#FFFFFF","#E30A17"], stadium: "Atatürk Olympic", capacity: 76092, reputation: 16, region: Region.TURKEY },
  { name: "Ukraina", continent: "Europe", tier: 2, colors: ["#005BBB","#FFD500","#005BBB"], stadium: "NSK Olimpiyskiy", capacity: 70050, reputation: 13, region: Region.EX_USSR },
  { name: "Walia", continent: "Europe", tier: 3, colors: ["#FFFFFF","#D30731","#006400"], stadium: "Millennium Stadium", capacity: 74500, reputation: 11, region: Region.ENGLAND },
  { name: "Węgry", continent: "Europe", tier: 3, colors: ["#CD2A3E","#FFFFFF","#436F4D"], stadium: "Puskás Aréna", capacity: 67215, reputation: 12, region: Region.HUNGARIAN },
  { name: "Włochy", continent: "Europe", tier: 1, colors: ["#009246","#FFFFFF","#CE2B37"], stadium: "Stadio Olimpico", capacity: 70634, reputation: 19, region: Region.ITALY },
  { name: "Wyspy Owcze", continent: "Europe", tier: 5, colors: ["#FFFFFF","#0035AD","#D21034"], stadium: "Tórsvøllur", capacity: 6040, reputation: 3, region: Region.SCANDINAVIA },
  { name: "Anglia", continent: "Europe", tier: 1, colors: ["#FFFFFF","#C8102E","#FFFFFF"], stadium: "Wembley", capacity: 90000, reputation: 20, region: Region.ENGLAND }
]
