export const NATIONAL_TEAMS_CONCACAF = [
  { name: "Stany Zjednoczone", continent: "North America", tier: 1, colors: ['#B22234','#FFFFFF','#3C3B6E'], stadium: "MetLife Stadium", capacity: 82500, reputation: 13 },
  { name: "Meksyk", continent: "North America", tier: 1, colors: ['#006847','#FFFFFF','#CE1126'], stadium: "Estadio Azteca", capacity: 87000, reputation: 14 },
  { name: "Kanada", continent: "North America", tier: 1, colors: ['#D52B1E','#FFFFFF','#D52B1E'], stadium: "BMO Field", capacity: 30000, reputation: 12 },
  { name: "Kostaryka", continent: "North America", tier: 2, colors: ['#002B7F','#FFFFFF','#CE1126'], stadium: "Estadio Nacional", capacity: 35000, reputation: 11 },
  { name: "Panama", continent: "North America", tier: 2, colors: ['#0052A5','#FFFFFF','#EF3340'], stadium: "Estadio Rommel Fernández", capacity: 32000, reputation: 10 },
  { name: "Honduras", continent: "North America", tier: 2, colors: ['#0073CF','#FFFFFF','#0073CF'], stadium: "Estadio Olímpico Metropolitano", capacity: 38000, reputation: 10 },
  { name: "Salwador", continent: "North America", tier: 2, colors: ['#0F47AF','#FFFFFF','#0F47AF'], stadium: "Estadio Cuscatlán", capacity: 53000, reputation: 9 },
  { name: "Gwatemala", continent: "North America", tier: 3, colors: ['#4997D0','#FFFFFF','#4997D0'], stadium: "Estadio Doroteo Guamuch Flores", capacity: 26000, reputation: 8 },
  { name: "Nikaragua", continent: "North America", tier: 3, colors: ['#0067C6','#FFFFFF','#0067C6'], stadium: "Estadio Nacional de Fútbol", capacity: 15000, reputation: 7 },
  { name: "Belize", continent: "North America", tier: 5, colors: ['#003F87','#FFFFFF','#CE1126'], stadium: "FFB Stadium", capacity: 5000, reputation: 4 },
  { name: "Jamajka", continent: "North America", tier: 2, colors: ['#009B3A','#FED100','#000000'], stadium: "Independence Park", capacity: 35000, reputation: 10 },
  { name: "Trynidad i Tobago", continent: "North America", tier: 2, colors: ['#CE1126','#FFFFFF','#000000'], stadium: "Hasely Crawford Stadium", capacity: 23000, reputation: 9 },
  { name: "Haiti", continent: "North America", tier: 2, colors: ['#00209F','#D21034','#FFFFFF'], stadium: "Stade Sylvio Cator", capacity: 15000, reputation: 9 },
  { name: "Curaçao", continent: "North America", tier: 2, colors: ['#0033A0','#FFD100','#CE1126'], stadium: "Ergilio Hato Stadium", capacity: 15000, reputation: 9 },
  { name: "Surinam", continent: "North America", tier: 2, colors: ['#377E3F','#FFFFFF','#B40A2D'], stadium: "André Kamperveen Stadium", capacity: 6000, reputation: 9 },
  { name: "Kuba", continent: "North America", tier: 3, colors: ['#002A8F','#FFFFFF','#CF142B'], stadium: "Estadio Pedro Marrero", capacity: 30000, reputation: 8 },
  { name: "Republika Dominikany", continent: "North America", tier: 3, colors: ['#002D62','#FFFFFF','#CE1126'], stadium: "Estadio Cibao FC", capacity: 14000, reputation: 8 },
  { name: "Panama", continent: "North America", tier: 2, colors: ['#0052A5','#FFFFFF','#EF3340'], stadium: "Estadio Rommel Fernández", capacity: 32000, reputation: 10 },
  { name: "Honduras", continent: "North America", tier: 2, colors: ['#0073CF','#FFFFFF','#0073CF'], stadium: "Estadio Olímpico Metropolitano", capacity: 38000, reputation: 10 },
  { name: "Antigua i Barbuda", continent: "North America", tier: 4, colors: ['#000000','#CE1126','#FFFFFF'], stadium: "Sir Vivian Richards Stadium", capacity: 10000, reputation: 5 },
  { name: "Aruba", continent: "North America", tier: 4, colors: ['#418FDE','#FFD100','#CE1126'], stadium: "Guillermo Prospero Trinidad Stadium", capacity: 8000, reputation: 5 },
  { name: "Bahamy", continent: "North America", tier: 5, colors: ['#00ABC9','#FFD100','#000000'], stadium: "Thomas A. Robinson Stadium", capacity: 15000, reputation: 4 },
  { name: "Barbados", continent: "North America", tier: 4, colors: ['#00267F','#FFD100','#000000'], stadium: "Wildey Turf", capacity: 3000, reputation: 5 },
  { name: "Bermudy", continent: "North America", tier: 4, colors: ['#CE1126','#FFFFFF','#00247D'], stadium: "National Sports Centre", capacity: 8000, reputation: 6 },
  { name: "Dominika", continent: "North America", tier: 5, colors: ['#006B3F','#FFD100','#000000'], stadium: "Windsor Park", capacity: 12000, reputation: 4 },
  { name: "Grenada", continent: "North America", tier: 4, colors: ['#CE1126','#FFD100','#006B3F'], stadium: "Kirani James Athletic Stadium", capacity: 8000, reputation: 5 },
  { name: "Kajmany", continent: "North America", tier: 5, colors: ['#00247D','#FFFFFF','#CF142B'], stadium: "Truman Bodden Sports Complex", capacity: 3000, reputation: 4 },
  { name: "Montserrat", continent: "North America", tier: 5, colors: ['#00247D','#FFFFFF','#CF142B'], stadium: "Blakes Estate Stadium", capacity: 3000, reputation: 3 },
  { name: "Saint Kitts i Nevis", continent: "North America", tier: 4, colors: ['#009E60','#FCD116','#CE1126'], stadium: "Warner Park Stadium", capacity: 8000, reputation: 5 },
  { name: "Saint Lucia", continent: "North America", tier: 4, colors: ['#6CF','#FFD100','#000000'], stadium: "Daren Sammy Cricket Ground", capacity: 15000, reputation: 5 },
  { name: "Saint Vincent i Grenadyny", continent: "North America", tier: 4, colors: ['#0052A5','#FFD100','#009E60'], stadium: "Arnos Vale Stadium", capacity: 18000, reputation: 5 },
  { name: "Turks i Caicos", continent: "North America", tier: 5, colors: ['#00247D','#FFFFFF','#CF142B'], stadium: "TCIFA National Academy", capacity: 3000, reputation: 3 }
]


