export const BALTIC_MALE_FIRSTNAMES = [
  "Markas", "Benas", "Jonas", "Motiejus", "Matas", "Nojus", "Lukas", "Jokūbas", "Leonas", "Adomas",
  "Herkus", "Dominykas", "Augustas", "Dovydas", "Kajus", "Mantas", "Vytautas", "Algirdas", "Gediminas", "Mindaugas",
  "Tomas", "Paulius", "Andrius", "Marius", "Arūnas", "Darius", "Gintaras", "Kęstutis", "Rimas", "Saulius",
  "Tauras", "Vilius", "Žygimantas", "Aivaras", "Antanas", "Artūras", "Edvinas", "Eimantas", "Ignas", "Justinas",
  "Karolis", "Linas", "Naglis", "Oskaras", "Povilas", "Raimundas", "Rolandas", "Simonas", "Tadas", "Vaidas",
  "Vaidotas", "Valdas", "Vygantas", "Žilvinas", "Ąžuolas", "Rytis", "Vytis", "Girius", "Rokas", "Deividas",
  "Olivers", "Roberts", "Marks", "Gustavs", "Emīls", "Daniels", "Markuss", "Adriāns", "Kārlis", "Aleksandrs",
  "Jēkabs", "Ernests", "Ralfs", "Dominiks", "Tomass", "Artūrs", "Ričards", "Maksims", "Toms", "Teodors",
  "Jānis", "Reinis", "Kristers", "Lūkass", "Edgars", "Māris", "Aivars", "Andris", "Juris", "Artjoms",
  "Nikolajs", "Oskars", "Pauls", "Rihards", "Valters", "Viktors", "Zigurds", "Dainis", "Gatis", "Ivars",
  "Kaspars", "Mārtiņš", "Pēteris", "Raitis", "Sandis", "Uldis", "Viesturs", "Ziedonis", "Edijs", "Ģirts",
  "Ingus", "Krišjānis", "Lauris", "Mihails", "Niks", "Rūdolfs", "Tālis", "Agnis", "Aigars", "Ainārs",
  "Aivis", "Alberts", "Andrejs", "Georgs", "Mark", "Hugo", "Robin", "Miron", "Lucas", "Karl",
  "Aron", "Mattias", "Sebastian", "Oskar", "Artur", "Leon", "Oliver", "Rasmus", "Kristofer", "Henri",
  "Nikita", "Jakob", "Martin", "Aleksandr", "Sergei", "Vladimir", "Andrei", "Andres", "Toomas", "Margus",
  "Indrek", "Peeter", "Priit", "Marko", "Jaan", "Jüri", "Mihkel", "Mati", "Ivo", "Ott",
  "Otto", "Hendrik", "Erik", "Felix", "Gregor", "Johannes", "Kaspar", "Timur", "Romet", "Jasper",
  "Joosep", "Konrad", "Mikk", "Kristjan", "Taavi", "Siim", "Rauno", "Mart", "Tanel", "Kevin",
  "Maksim", "Dmitri", "Igor", "Anton", "Deniss", "Bruno", "Feliks", "Osvald", "Aivar", "Ain",
  "Aleksei", "Vlad", "Yegor", "Antero", "Kaarel", "Silvar", "Ken", "Paul", "Jakob", "Matilde"
];

export const BALTIC_MALE_LASTNAMES = [
  "Jankauskas", "Kazlauskas", "Petrauskas", "Stankevičius", "Vasiliauskas", "Butkus", "Urbonas", "Kavaliauskas", "Žukauskas", "Balčiūnas",
  "Černiauskas", "Grigaliūnas", "Kairys", "Paulauskas", "Ramanauskas", "Sakalauskas", "Vaitkus", "Zinkevičius", "Adomaitis", "Baranauskas",
  "Daugėla", "Gedvilas", "Ivanauskas", "Jonaitis", "Klimas", "Laurinavičius", "Mažeika", "Navickas", "Petkevičius", "Rimkus",
  "Simutis", "Tamulevičius", "Valaitis", "Venckus", "Žemaitis", "Bērziņš", "Kalniņš", "Ozoliņš", "Jansons", "Ozols",
  "Liepiņš", "Krūmiņš", "Balodis", "Eglītis", "Siliņš", "Skuja", "Strazdiņš", "Riekstiņš", "Saulītis", "Priede",
  "Vanags", "Vilciņš", "Zaķis", "Puriņš", "Kļaviņš", "Āboliņš", "Kalniņš", "Berzins", "Ivanovs", "Kalnins",
  "Tamm", "Saar", "Sepp", "Kask", "Mägi", "Kukk", "Rebane", "Koppel", "Karu", "Ilves",
  "Lepik", "Pärn", "Kivi", "Kuusk", "Järv", "Põder", "Lepp", "Laas", "Oja", "Kangur",
  "Raid", "Roots", "Sild", "Toom", "Vare", "Aasmäe", "Allik", "Eesti", "Haas", "Jõgi",
  "Kallas", "Kõiv", "Lille", "Mets", "Nõmm", "Puu", "Raud", "Soo", "Tammik", "Vesi",
  "Aleksejev", "Ivanov", "Petrov", "Smirnov", "Popov", "Sokolov", "Morozov", "Volkov", "Lebedev", "Kuznetsov",
  "Novikov", "Mihhailov", "Fedorov", "Stepanov", "Nikolaev", "Andreev", "Petrenko", "Kovalenko", "Bondarenko", "Tkachenko",
  "Shevchenko", "Kovalchuk", "Melnyk", "Kravchenko", "Savchenko", "Boyko", "Marchenko", "Lysenko", "Koval", "Pavlenko",
  "Litvin", "Zaitsev", "Orlov", "Kozlov", "Novak", "Kovalyov", "Moroz", "Pavlov", "Semenov", "Ermakov",
  "Dmitriev", "Antonov", "Gusev", "Tikhonov", "Frolov", "Sergeev", "Romanov", "Zaharov", "Borisov", "Maksimov",
  "Sidorov", "Osipov", "Belov", "Vorobyov", "Solovyov", "Kolesnikov", "Karpov", "Afanasiev", "Vlasov", "Maslov",
  "Isakov", "Tarasov", "Martynov", "Sviridov", "Yakovlev", "Polyakov", "Ponomarev", "Gorbunov", "Kudryavtsev", "Krylov",
  "Belyaev", "Bogdanov", "Voronin", "Vinogradov", "Medvedev", "Abramov", "Krasnov", "Sobolev", "Titov", "Makarov",
  "Gavrilov", "Antipov", "Filippov", "Grigoriev", "Kuzmin", "Davydov", "Melnikov", "Denisov", "Gromov", "Fomin",
  "Klimov", "Petukhov", "Kochetkov", "Gorbachev", "Kryukov", "Belyakov", "Alekseev", "Savin", "Rybakov", "Suvorov"
];