export const BRAZILIAN_MALE_FIRSTNAMES = [
  'José', 'João', 'Antonio', 'Francisco', 'Carlos', 'Paulo', 'Pedro', 'Lucas', 'Luiz', 'Marcos',
  'Miguel', 'Gabriel', 'Arthur', 'Heitor', 'Davi', 'Bernardo', 'João Miguel', 'João Pedro', 'Enzo', 'Enzo Gabriel',
  'Rafael', 'Felipe', 'Rodrigo', 'Mateus', 'Matheus', 'Gustavo', 'Bruno', 'Eduardo', 'Daniel', 'Marcelo',
  'Thiago', 'Tiago', 'André', 'Fernando', 'Ricardo', 'Roberto', 'Jorge', 'Alexandre', 'Vinicius', 'Leonardo',
  'Henrique', 'Caio', 'Cauã', 'Cauê', 'Kaique', 'Kauan', 'Luan', 'Ryan', 'Samuel', 'Theo',
  'Noah', 'Benício', 'Levi', 'Ravi', 'Gael', 'Matteo', 'Bento', 'Estêvão', 'Felipe', 'Francisco',
  'Afonso', 'Alejandro', 'Alvaro', 'Amarildo', 'Anderson', 'Ângelo', 'Antônio', 'Arnaldo', 'Augusto', 'Breno',
  'Caetano', 'César', 'Cláudio', 'Cristiano', 'Davi Lucas', 'Diego', 'Diogo', 'Dionísio', 'Douglas', 'Edson',
  'Eduardo', 'Elton', 'Emerson', 'Enrico', 'Eric', 'Erik', 'Fábio', 'Fabrício', 'Fausto', 'Filipe',
  'Flávio', 'Frederico', 'Gabriel', 'Gilberto', 'Giovanni', 'Guilherme', 'Hélio', 'Hugo', 'Igor', 'Ítalo',
  'Ivan', 'Jair', 'João Lucas', 'João Vitor', 'Jonas', 'Júlio', 'Júnior', 'Ladislau', 'Lauro', 'Leandro',
  'Leônidas', 'Léo', 'Lourenço', 'Luciano', 'Luís', 'Manoel', 'Manuel', 'Marcel', 'Márcio', 'Marco',
  'Mário', 'Maurício', 'Murilo', 'Natan', 'Nelson', 'Nicolas', 'Nícolas', 'Otávio', 'Pablo', 'Patrick',
  'Paulo Henrique', 'Pedro Henrique', 'Philippe', 'Raimundo', 'Raul', 'Renan', 'Renato', 'Rian', 'Richard',
  'Roberto', 'Robson', 'Rodrigo', 'Rogério', 'Romário', 'Rômulo', 'Ronaldo', 'Rúben', 'Sandro', 'Sebastião',
  'Sérgio', 'Silas', 'Simão', 'Tadeu', 'Tarcísio', 'Thales', 'Théo', 'Thiago', 'Thomas', 'Tomás',
  'Valdir', 'Valter', 'Vanderlei', 'Vitor', 'Vitória', 'Wagner', 'Waldir', 'Washington', 'Wesley', 'William',
  'Xavier', 'Yago', 'Yuri', 'Zé', 'Zeca', 'Abel', 'Adalberto', 'Adão', 'Ademir', 'Adriano',
  'Aécio', 'Ailton', 'Airton', 'Alan', 'Alberto', 'Alcides', 'Aldo', 'Alex', 'Allan', 'Aloísio',
  'Aluísio', 'Amadeu', 'Américo', 'Anselmo', 'Antenor', 'Aparecido', 'Arlindo', 'Armando', 'Arnaldo', 'Artur',
  'Ataíde', 'Aureliano', 'Aurélio', 'Baltazar', 'Bartolomeu', 'Basílio', 'Batista', 'Belmiro', 'Benedito', 'Benjamim',
  'Bento', 'Bernardo', 'Boanerges', 'Bonifácio', 'Breno', 'Caetano', 'Cândido', 'Cássio', 'Celso', 'Cícero',
  'Cláudio', 'Clodomiro', 'Clóvis', 'Constantino', 'Cristiano', 'Cristóvão', 'Damião', 'Dante', 'Dário', 'Davi',
  'Décio', 'Demétrio', 'Denis', 'Deusdedit', 'Djalma', 'Domingos', 'Donato', 'Dorival', 'Duílio', 'Durval',
  'Edilson', 'Edmar', 'Edmilson', 'Edson', 'Eduardo', 'Eládio', 'Elias', 'Elísio', 'Elton', 'Emanuel',
  'Emílio', 'Enéas', 'Ernesto', 'Estácio', 'Eugênio', 'Eurico', 'Evaristo', 'Everaldo', 'Expedito', 'Fábio',
  'Fabricio', 'Faustino', 'Fausto', 'Feliciano', 'Félix', 'Fernandes', 'Firmino', 'Flávio', 'Florêncio', 'Fortunato',
  'Francisco', 'Franco', 'Frederico', 'Gabriel', 'Geraldo', 'Germano', 'Getúlio', 'Gideão', 'Gil', 'Gilberto',
  'Glauber', 'Glauco', 'Gonçalo', 'Gregório', 'Guilherme', 'Gustavo', 'Hamilton', 'Haroldo', 'Hélio', 'Henrique',
  'Hermes', 'Hilário', 'Humberto', 'Ibrahim', 'Idalício', 'Inácio', 'Irineu', 'Isaías', 'Ismael', 'Israel',
  'Ivan', 'Ivo', 'Jacinto', 'Jackson', 'Jaime', 'Jair', 'Jairo', 'James', 'Jânio', 'Jardel',
  'Jarbas', 'Jeferson', 'Jerônimo', 'Jesuíno', 'João', 'Joaquim', 'Joel', 'Jonas', 'Jorge', 'José',
  'Josué', 'Joviano', 'Juarez', 'Júlio', 'Júnior', 'Juraci', 'Justiniano', 'Juvenal', 'Kléber', 'Laerte',
  'Lauro', 'Leandro', 'Leôncio', 'Leopoldo', 'Lídio', 'Lino', 'Lourenço', 'Lucas', 'Luciano', 'Luís',
  'Maciel', 'Manoel', 'Manuel', 'Marcelo', 'Márcio', 'Marco', 'Marcos', 'Mário', 'Martinho', 'Mateus',
  'Matheus', 'Maurício', 'Mauro', 'Máximo', 'Melquíades', 'Micael', 'Miguel', 'Milton', 'Moacir', 'Moises',
  'Murilo', 'Nabor', 'Nataniel', 'Nélio', 'Nelson', 'Nestor', 'Newton', 'Nicolau', 'Nilo', 'Nilton',
  'Nivaldo', 'Norberto', 'Olavo', 'Olímpio', 'Onofre', 'Oriovaldo', 'Oscar', 'Osman', 'Osmar', 'Osvaldo',
  'Otacílio', 'Otávio', 'Otoniel', 'Ovaldo', 'Ozeias', 'Pablo', 'Pascoal', 'Patrício', 'Paulo', 'Pedro',
  'Pelé', 'Percival', 'Péricles', 'Pierre', 'Plínio', 'Policarpo', 'Prudente', 'Quintino', 'Rafael', 'Raimundo',
  'Ramiro', 'Raúl', 'Reginaldo', 'Reinaldo', 'Renan', 'Renato', 'Ricardo', 'Roberto', 'Robson', 'Rodolfo',
  'Rodrigo', 'Rogério', 'Romário', 'Rômulo', 'Ronald', 'Ronaldo', 'Roque', 'Rui', 'Ruy', 'Sálvio',
  'Samuel', 'Sandoval', 'Sandro', 'Santiago', 'Saulo', 'Sebastião', 'Sérgio', 'Severino', 'Sidney', 'Silas',
  'Silvestre', 'Simão', 'Simeão', 'Sílvio', 'Simão', 'Sotero', 'Stanislau', 'Tadeu', 'Tarcísio', 'Tasso',
  'Teodoro', 'Teófilo', 'Terêncio', 'Thales', 'Théo', 'Thiago', 'Thomas', 'Thomaz', 'Tibério', 'Timóteo',
  'Tobias', 'Tomás', 'Tristão', 'Ubirajara', 'Ubiratan', 'Ulisses', 'Urbano', 'Valdemar', 'Valdir', 'Valter',
  'Vanderlei', 'Vasco', 'Venâncio', 'Venceslau', 'Vicente', 'Victor', 'Vidal', 'Vinícius', 'Virgílio', 'Vítor',
  'Wagner', 'Waldemar', 'Waldir', 'Washington', 'Wellington', 'Wesley', 'William', 'Wilson', 'Xavier', 'Yago',
  'Yuri', 'Zacarias', 'Zeno', 'Zé', 'Zeca'
];

export const BRAZILIAN_MALE_LASTNAMES = [
  'Silva', 'Santos', 'Oliveira', 'Souza', 'Pereira', 'Ferreira', 'Lima', 'Alves', 'Rodrigues', 'Costa',
  'Sousa', 'Gomes', 'Nascimento', 'Araujo', 'Ribeiro', 'Almeida', 'Jesus', 'Barbosa', 'Soares', 'Carvalho',
  'Martins', 'Rocha', 'Dias', 'Nunes', 'Freitas', 'Conceicao', 'Melo', 'Moreira', 'Cardoso', 'Reis',
  'Cruz', 'Goncalves', 'Andrade', 'Mendes', 'Teixeira', 'Vieira', 'Machado', 'Marques', 'Fernandes', 'Lopes',
  'Santana', 'Bezerra', 'Campos', 'Moraes', 'Borges', 'Monteiro', 'Moura', 'Miranda', 'Castro', 'Sampaio',
  'Siqueira', 'Azevedo', 'Cavalcante', 'Coelho', 'Correia', 'Duarte', 'Figueiredo', 'Fonseca', 'Garcia', 'Leite',
  'Macedo', 'Medeiros', 'Moraes', 'Morais', 'Neves', 'Pinto', 'Queiroz', 'Ramos', 'Santos', 'Silveira',
  'Torres', 'Vargas', 'Vieira', 'Xavier', 'Abreu', 'Aguiar', 'Amaral', 'Amorim', 'Andrade', 'Anjos',
  'Antunes', 'Aparecido', 'Araujo', 'Assis', 'Azevedo', 'Baptista', 'Barreto', 'Batista', 'Borges', 'Brandao',
  'Brito', 'Bueno', 'Cabral', 'Caldas', 'Caldeira', 'Camargo', 'Campos', 'Cardoso', 'Carneiro', 'Carvalho',
  'Castilho', 'Castro', 'Cavalcanti', 'Chaves', 'Clemente', 'Coelho', 'Conceicao', 'Correa', 'Costa', 'Coutinho',
  'Cruz', 'Cunha', 'Dantas', 'Dias', 'Diniz', 'Domingues', 'Duarte', 'Farias', 'Fernandes', 'Ferreira',
  'Figueira', 'Figueiredo', 'Fonseca', 'Franco', 'Freitas', 'Furtado', 'Gama', 'Garcia', 'Gomes', 'Goncalves',
  'Guerra', 'Guimaraes', 'Henrique', 'Jesus', 'Leal', 'Leite', 'Lima', 'Lopes', 'Loureiro', 'Luz',
  'Macedo', 'Machado', 'Magalhaes', 'Marques', 'Martins', 'Medeiros', 'Melo', 'Mendes', 'Mendonca', 'Miranda',
  'Monteiro', 'Montes', 'Moraes', 'Morais', 'Moreira', 'Moura', 'Muniz', 'Nascimento', 'Neves', 'Nogueira',
  'Nunes', 'Oliveira', 'Pacheco', 'Paiva', 'Peixoto', 'Pereira', 'Pimentel', 'Pinheiro', 'Pinto', 'Pires',
  'Queiroz', 'Ramos', 'Reis', 'Rezende', 'Ribeiro', 'Rocha', 'Rodrigues', 'Romao', 'Sampaio', 'Santana',
  'Santiago', 'Santos', 'Saraiva', 'Silva', 'Silveira', 'Siqueira', 'Soares', 'Sobrinho', 'Sousa', 'Souza',
  'Tavares', 'Teixeira', 'Torres', 'Valente', 'Valeriano', 'Vargas', 'Vasconcelos', 'Ventura', 'Vieira', 'Xavier',
  'Afonso', 'Aguiar', 'Albuquerque', 'Alencar', 'Almeida', 'Alves', 'Amaral', 'Andrade', 'Antunes', 'Araujo',
  'Assuncao', 'Azevedo', 'Barbosa', 'Barros', 'Batista', 'Bezerra', 'Bittencourt', 'Borges', 'Brandao', 'Brito',
  'Bueno', 'Cabral', 'Caldas', 'Camargo', 'Campos', 'Cardoso', 'Carneiro', 'Carvalho', 'Castro', 'Cavalcanti',
  'Chaves', 'Clemente', 'Coelho', 'Conceicao', 'Correa', 'Costa', 'Couto', 'Cruz', 'Cunha', 'Dantas',
  'Dias', 'Diniz', 'Domingues', 'Duarte', 'Farias', 'Fernandes', 'Ferreira', 'Figueiredo', 'Fonseca', 'Franco',
  'Freitas', 'Furtado', 'Gama', 'Garcia', 'Gomes', 'Goncalves', 'Guimaraes', 'Henriques', 'Jesus', 'Leal',
  'Leite', 'Lima', 'Lopes', 'Loureiro', 'Machado', 'Magalhaes', 'Marques', 'Martins', 'Medeiros', 'Melo',
  'Mendes', 'Mendonca', 'Miranda', 'Monteiro', 'Moraes', 'Moreira', 'Moura', 'Nascimento', 'Neves', 'Nogueira',
  'Nunes', 'Oliveira', 'Pacheco', 'Paiva', 'Peixoto', 'Pereira', 'Pimentel', 'Pinheiro', 'Pinto', 'Pires',
  'Queiroz', 'Ramos', 'Reis', 'Ribeiro', 'Rocha', 'Rodrigues', 'Sampaio', 'Santana', 'Santos', 'Silva',
  'Silveira', 'Soares', 'Sousa', 'Souza', 'Tavares', 'Teixeira', 'Torres', 'Valente', 'Vieira', 'Xavier',
  'Abreu', 'Aguiar', 'Alencar', 'Almeida', 'Alves', 'Amaral', 'Andrade', 'Araujo', 'Azevedo', 'Barbosa',
  'Barros', 'Batista', 'Bezerra', 'Borges', 'Brandao', 'Brito', 'Cabral', 'Campos', 'Cardoso', 'Carvalho',
  'Castro', 'Cavalcanti', 'Coelho', 'Correa', 'Costa', 'Cruz', 'Cunha', 'Dias', 'Duarte', 'Fernandes',
  'Ferreira', 'Fonseca', 'Freitas', 'Garcia', 'Gomes', 'Goncalves', 'Guimaraes', 'Jesus', 'Leite', 'Lima',
  'Lopes', 'Machado', 'Marques', 'Martins', 'Medeiros', 'Melo', 'Mendes', 'Miranda', 'Monteiro', 'Moraes',
  'Moreira', 'Moura', 'Nascimento', 'Neves', 'Nogueira', 'Nunes', 'Oliveira', 'Pereira', 'Pinheiro', 'Pinto',
  'Ramos', 'Reis', 'Ribeiro', 'Rocha', 'Rodrigues', 'Santos', 'Silva', 'Silveira', 'Soares', 'Souza',
  'Teixeira', 'Torres', 'Vieira', 'Xavier'
];