export const GREEK_MALE_FIRSTNAMES = [
  "Giorgos", "Dimitris", "Nikos", "Christos", "Panagiotis", "Ioannis", "Konstantinos", "Alexandros", "Michalis", "Antonis",
  "Stavros", "Vassilis", "Thanasis", "Petros", "Sotiris", "Kostas", "Spyros", "Manolis", "Lefteris", "Yiannis",
  "Andreas", "Theodoros", "Pavlos", "Marios", "Savvas", "Kyriakos", "Charalambos", "Evangelos", "Filippos", "Stefanos",
  "Loukas", "Elias", "Achilleas", "Aristides", "Athanasios", "Dionysios", "Eleftherios", "Epaminondas", "Eustathios", "Georgios",
  "Ilias", "Konstantinos", "Lambros", "Leonidas", "Makarios", "Marinos", "Menelaos", "Neophytos", "Odysseas", "Orestis",
  "Pambos", "Panayiotis", "Paraskevas", "Phivos", "Photios", "Prokopis", "Rafail", "Sokratis", "Spyridon", "Stelios",
  "Stylianos", "Symeon", "Tassos", "Themistoklis", "Theofanis", "Thomas", "Timotheos", "Titos", "Vasileios", "Xenophon",
  "Zinon", "Adonis", "Agapios", "Akis", "Alexis", "Alkis", "Anastasios", "Andreas", "Angelos", "Antonis",
  "Apostolos", "Aris", "Aristarchos", "Aristodemos", "Aristofanis", "Aristos", "Athos", "Avgoustinos", "Avraam", "Charis",
  "Chariton", "Christakis", "Christodoulos", "Christoforos", "Chrysanthos", "Chrysostomos", "Damianos", "Demetrios", "Dimos", "Dionisis",
  "Doros", "Efthymios", "Elpidoforos", "Emmanouil", "Ermis", "Ermogenis", "Eugenios", "Eustathios", "Evripidis", "Filippos",
  "Fivos", "Fotios", "Fragkiskos", "Gavriel", "Gregoris", "Haralambos", "Haris", "Heraklis", "Iakovos", "Iason",
  "Ippokratis", "Isidoros", "Kleanthis", "Kostas", "Kyprianos", "Kyriakos", "Lambis", "Lambros", "Lazaros", "Lefkos",
  "Leon", "Leontios", "Loucas", "Louizos", "Loukis", "Makis", "Manos", "Manthos", "Markos", "Martinos",
  "Matthaios", "Melis", "Michail", "Mihalis", "Miltos", "Minas", "Nearchos", "Neoklis", "Nestor", "Nicos",
  "Odysseas", "Orestis", "Pambos", "Panos", "Pantelis", "Paris", "Parmenion", "Paschalis", "Petros", "Philippos",
  "Phivos", "Pieris", "Polycarpos", "Prodromos", "Rafail", "Renos", "Sakis", "Savvas", "Semos", "Sokratis",
  "Sotiris", "Spyridon", "Stavros", "Stefanos", "Stelios", "Stylianos", "Symeon", "Takis", "Tassos", "Thanasis",
  "Themistoklis", "Theodoros", "Theofanis", "Thomas", "Titos", "Tomas", "Vangelis", "Vasilis", "Vassilis", "Viktor",
  "Vlassis", "Xanthos", "Xenios", "Xenophon", "Yiannakis", "Yiannis", "Zinon", "Adam", "Alekos", "Alex",
  "Alexandros", "Alkis", "Anastasios", "Andreas", "Angelos", "Antonis", "Apostolos", "Aris", "Aristides", "Aristodemos",
  "Athanasios", "Charalampos", "Charis", "Christodoulos", "Christoforos", "Chrysanthos", "Demetrios", "Dionysios", "Doros", "Efthymios",
  "Eleftherios", "Emmanouil", "Ermis", "Eugenios", "Evangelos", "Filippos", "Fotios", "Georgios", "Giorgos", "Gregoris",
  "Haralambos", "Haris", "Heraklis", "Ilias", "Ioannis", "Ippokratis", "Kleanthis", "Konstantinos", "Kostas", "Kyriakos",
  "Lambros", "Leonidas", "Loukas", "Makarios", "Manolis", "Marinos", "Matthaios", "Michalis", "Miltos", "Neophytos",
  "Nikolaos", "Odysseas", "Orestis", "Panagiotis", "Pantelis", "Paraskevas", "Petros", "Philippos", "Rafail", "Sokratis",
  "Sotiris", "Spyridon", "Stavros", "Stefanos", "Stelios", "Stylianos", "Symeon", "Theodoros", "Thomas", "Timotheos",
  "Vassilis", "Xenophon", "Yiannis", "Zinon", "Achilleas", "Adonis", "Agapios", "Alexis", "Alkis", "Anastasios",
  "Andreas", "Angelos", "Antonis", "Apostolos", "Aris", "Aristides", "Athanasios", "Charalampos", "Christodoulos", "Christos",
  "Demetrios", "Dionysios", "Eleftherios", "Emmanouil", "Evangelos", "Filippos", "Fotios", "Georgios", "Giorgos", "Ilias",
  "Ioannis", "Konstantinos", "Kostas", "Kyriakos", "Lambros", "Leonidas", "Loukas", "Manolis", "Michalis", "Nikolaos",
  "Panagiotis", "Pantelis", "Petros", "Sotiris", "Spyridon", "Stavros", "Stelios", "Theodoros", "Thomas", "Vassilis",
  "Yiannis", "Zinon"
];

export const GREEK_MALE_LASTNAMES = [
  "Papadopoulos", "Papadopoulou", "Georgiou", "Papageorgiou", "Nikolaou", "Ioannou", "Christodoulou", "Konstantinou", "Michailidis", "Panagiotou",
  "Dimitriou", "Alexandrou", "Vasilopoulos", "Kostas", "Spyropoulos", "Antoniou", "Stavropoulos", "Theodorou", "Pavlou", "Sotiriou",
  "Kyriakou", "Charalambous", "Evangelou", "Filippos", "Manolopoulos", "Lefteris", "Yiannis", "Andreas", "Theodoridis", "Panagiotidis",
  "Savvas", "Kyriakos", "Marios", "Stelios", "Lambrou", "Petridis", "Athanasiou", "Eleftheriou", "Panayiotou", "Christou",
  "Vasilou", "Markou", "Evangelou", "Paraskevas", "Stylianou", "Neophytou", "Kostas", "Louca", "Mavrou", "Hadjigeorgiou",
  "Hadjichristodoulou", "Hadjipavlou", "Hadjimichael", "Hadjinicolaou", "Hadjipetrou", "Hadjisavvas", "Hadjikostis", "Hadjimichael", "Hadjistyllis", "Hadjipetrou",
  "Andreou", "Antoniou", "Charalambous", "Christodoulou", "Constantinou", "Demetriou", "Eleftheriou", "Evangelou", "Georgiou", "Ioannou",
  "Kleanthous", "Kyriacou", "Lambrou", "Louca", "Markou", "Michael", "Nicolaou", "Panagiotou", "Papadopoulos", "Pavlou",
  "Petrides", "Savva", "Socratous", "Spyrou", "Stavrou", "Stylianou", "Theodorou", "Vasilou", "Zachariou", "Zenonos",
  "Agathangelou", "Alexandrou", "Anastasiou", "Aristidou", "Avraam", "Bakirtzis", "Charalambides", "Charitou", "Christofides", "Chrysanthou",
  "Chrysostomou", "Constantinides", "Demetriades", "Dimitriou", "Efthymiou", "Eliades", "Ellinas", "Erotokritou", "Fotiou", "Frangou",
  "Georgiadis", "Georgiades", "Gregoriou", "Hadjidemetriou", "Hadjinicolaou", "Hadjipavlou", "Hadjisavvas", "Hadjitheodorou", "Hadjikyriakou", "Iacovou",
  "Ioannides", "Kakoullis", "Kallis", "Kalogirou", "Karageorgiou", "Karamallis", "Katsaros", "Kleanthous", "Konstantinou", "Koumi",
  "Kourou", "Kyriakides", "Kyriakou", "Lambrou", "Leontiou", "Loizou", "Loucaides", "Makedonas", "Mallis", "Manoli",
  "Markides", "Matsas", "Mavrommatis", "Michaelides", "Mina", "Mitsis", "Moullos", "Neophytou", "Nikolaides", "Nikolaou",
  "Papageorgiou", "Papantoniou", "Paphitis", "Paraskevas", "Patsalides", "Pericleous", "Petrakis", "Philippou", "Pierides", "Pitsillides",
  "Polyviou", "Prodromou", "Psaltis", "Raptis", "Savidis", "Savvides", "Sideris", "Sofocleous", "Soteriou", "Stavrides",
  "Stylianides", "Symeou", "Symeonides", "Themistocleous", "Theocharous", "Theodorides", "Theofanous", "Tofarides", "Toma", "Tsiakkiros",
  "Tsikkos", "Tsolakis", "Varnava", "Vasileiou", "Vassiliou", "Xenophontos", "Yiallouris", "Zachariades", "Zembylas", "Zenios",
  "Zervos", "Adamopoulos", "Alexopoulos", "Anagnostou", "Anastasiadis", "Andreopoulos", "Angelopoulos", "Antoniadis", "Argyropoulos", "Athanasopoulos",
  "Christopoulos", "Diamantis", "Dimitriadis", "Economou", "Efthymiadis", "Fotiadis", "Georgiadis", "Giannakopoulos", "Giannopoulos", "Grigoriadis",
  "Hadjipavlou", "Ioannidis", "Kalogeropoulos", "Karagiannis", "Karamanlis", "Karamouzis", "Katsouris", "Kefalas", "Konstantinidis", "Kostopoulos",
  "Koulouris", "Kouris", "Kyriakidis", "Lazaridis", "Leontidis", "Makridis", "Manolakis", "Markopoulos", "Mavridis", "Michailidis",
  "Nikolaidis", "Panagiotidis", "Papadakis", "Papadimitriou", "Papakonstantinou", "Papathanasiou", "Pappas", "Paraskevopoulos", "Pavlidis", "Petridis",
  "Raptis", "Samaras", "Sideris", "Sotiropoulos", "Stavridis", "Stefanidis", "Stylianou", "Theodoridis", "Tsakiris", "Tsoukalas",
  "Vasilakis", "Vasilopoulos", "Vlachos", "Voulgaris", "Zafeiriou", "Zisis", "Zografos"
];