export const ISRAELI_MALE_FIRSTNAMES = [
  "David", "Yosef", "Moshe", "Avraham", "Yitzhak", "Yaakov", "Aharon", "Yehuda", "Shimon", "Levi",
  "Yehoshua", "Yonatan", "Daniel", "Eitan", "Noam", "Ariel", "Omer", "Itay", "Uri", "Nadav",
  "Eyal", "Gilad", "Amir", "Barak", "Ido", "Liran", "Shahar", "Tal", "Ron", "Matan",
  "Shai", "Nimrod", "Ziv", "Ori", "Alon", "Dvir", "Ofir", "Roi", "Guy", "Ben",
  "Yair", "Asaf", "Tomer", "Yoav", "Yuval", "Erez", "Hillel", "Boaz", "Elad", "Gal",
  "Itamar", "Lior", "Nir", "Ran", "Shaked", "Shlomi", "Sagi", "Yogev", "Yotam", "Ze'ev",
  "Adam", "Aviv", "Bar", "Doron", "Eli", "Gideon", "Hadar", "Ilan", "Kfir", "Lev",
  "Maor", "Natan", "Omri", "Peleg", "Raz", "Shmuel", "Tzur", "Udi", "Vered", "Yarden",
  "Zohar", "Amit", "Benny", "Carmel", "Dani", "Eden", "Elisha", "Eran", "Gadi", "Haim",
  "Imri", "Jared", "Kobi", "Lavi", "Meir", "Naor", "Oded", "Paz", "Rafi", "Sagiv",
  "Shimon", "Tali", "Uriel", "Yehiel", "Zack", "Aaron", "Abraham", "Adi", "Akiva", "Amos",
  "Avi", "Aviel", "Aviad", "Avishai", "Avner", "Ayal", "Baruch", "Ben Zion", "Binyamin", "Chaim",
  "Dovid", "Dov", "Efraim", "Ehud", "Elazar", "Eliav", "Eliyahu", "Ephraim", "Ezra", "Gershon",
  "Hagai", "Hanan", "Harel", "Hashim", "Hershel", "Hillel", "Isaac", "Ishai", "Israel", "Itzik",
  "Jacob", "Jonathan", "Judah", "Kahana", "Koby", "Leib", "Menashe", "Menachem", "Mordechai", "Moti",
  "Nachman", "Naftali", "Netanel", "Nissim", "Noach", "Noy", "Oren", "Pinchas", "Rafael", "Reuven",
  "Ronni", "Rotem", "Saul", "Shalom", "Shaul", "Shlomo", "Shmuel", "Shneur", "Shraga", "Shuki",
  "Simcha", "Solomon", "Tanhum", "Tuvia", "Tzvi", "Uzi", "Yaacov", "Yanky", "Yaron", "Yehoshua",
  "Yehuda", "Yishai", "Yisrael", "Yitzchak", "Yochanan", "Yoni", "Yossi", "Zalman", "Zev", "Zvi",
  "Arik", "Asher", "Avihu", "Avraham", "Benaya", "Binyamin", "Chanan", "Daniyel", "Eitan", "Elchanan",
  "Eli", "Elyakim", "Emanuel", "Erez", "Gavriel", "Gershon", "Haim", "Hanan", "Hod", "Idan",
  "Ilay", "Inbar", "Itay", "Keren", "Liel", "Matityahu", "Meidad", "Menachem", "Michal", "Mordechai",
  "Moshe", "Nadav", "Naftali", "Netanel", "Nir", "Noam", "Ofer", "Ophir", "Ori", "Orr",
  "Oshri", "Otniel", "Oz", "Pinchas", "Rami", "Ronen", "Rotem", "Roy", "Shai", "Shalom",
  "Shaul", "Shay", "Shimon", "Shlomi", "Shmuel", "Shoham", "Shuki", "Tal", "Tamir", "Tomer",
  "Tzion", "Uriel", "Yair", "Yaki", "Yaron", "Yehiel", "Yehonatan", "Yehoshua", "Yehuda", "Yishai",
  "Yitzhak", "Yoav", "Yonatan", "Yosef", "Yossi", "Yuval", "Ziv"
];

export const ISRAELI_MALE_LASTNAMES = [
  "Cohen", "Levy", "Mizrachi", "Peretz", "Bitton", "Azoulay", "David", "Mor", "Klein", "Friedman",
  "Goldberg", "Levin", "Shapiro", "Rosenberg", "Weiss", "Roth", "Kaplan", "Abramov", "Katz", "Ben David",
  "Ben Ezra", "Ben Zion", "Ben Yosef", "Ben Ari", "Ben Moshe", "Ben Shimon", "Ben Gurion", "Dayan", "Elias", "Farkash",
  "Golan", "Halevy", "Harari", "Hasson", "Hayun", "Herman", "Hoffman", "Israeli", "Kadosh", "Kahlon",
  "Kedem", "Keren", "Lahav", "Landau", "Lavi", "Lazar", "Levi", "Maman", "Maoz", "Marom",
  "Mashiach", "Mizrahi", "Morag", "Moshe", "Nagar", "Nahum", "Navon", "Neeman", "Nissan", "Ohana",
  "Oren", "Ovadia", "Paz", "Peled", "Perez", "Porat", "Rabin", "Rabinovich", "Rahamim", "Ram",
  "Rapaport", "Ravid", "Raz", "Regev", "Reuven", "Romano", "Rosen", "Rotem", "Saada", "Sabag",
  "Saban", "Sagi", "Salomon", "Sasson", "Schwartz", "Shalom", "Shamir", "Shapira", "Sharon", "Shemesh",
  "Shilo", "Shimon", "Shoham", "Shulman", "Silver", "Sinai", "Stern", "Suissa", "Tadmor", "Tal",
  "Tamir", "Tevet", "Toledano", "Tzur", "Vaknin", "Wasser", "Weinstein", "Yadin", "Yahav", "Yarkoni",
  "Yitzhaki", "Yosef", "Zadok", "Zamir", "Zohar", "Zuckerman", "Abadi", "Abecassis", "Abergel", "Abulafia",
  "Adler", "Aharoni", "Almog", "Amar", "Amram", "Arad", "Arbel", "Ashkenazi", "Avidan", "Avital",
  "Ayalon", "Azaria", "Barak", "Bar Ilan", "Bar Lev", "Barak", "Bass", "Ben Artzi", "Ben Haim", "Ben Harush",
  "Ben Ishay", "Ben Natan", "Ben Porat", "Ben Shalom", "Ben Yair", "Ben Yishai", "Berkowitz", "Bloch", "Blum", "Bouskila",
  "Braverman", "Chaim", "Cohen", "Dahan", "Dankner", "Dar", "Doron", "Eden", "Efrati", "Eisenberg",
  "Elbaz", "Eliezer", "Elkayam", "Elmaliach", "Elyashiv", "Eshkol", "Farkas", "Fogel", "Frankel", "Freund",
  "Gabai", "Gabay", "Gafni", "Gal", "Ganon", "Gavrieli", "Gefen", "Gershon", "Gil", "Golan",
  "Gold", "Goldman", "Gottlieb", "Greenberg", "Gross", "Gur", "Hadar", "Haim", "Halperin", "Harel",
  "Hasson", "Haziza", "Hershkovitz", "Hirsch", "Hofman", "Horowitz", "Idan", "Ilan", "Israeli", "Kadosh",
  "Kahan", "Kahana", "Kahn", "Kaminer", "Kantor", "Katz", "Kedar", "Kenan", "Keren", "Kessler",
  "Kfir", "Kishon", "Klausner", "Koch", "Kohn", "Kopel", "Koren", "Kramer", "Kushnir", "Lahav",
  "Landau", "Lapid", "Laufer", "Lavi", "Leibowitz", "Leibson", "Leitner", "Lerner", "Levi", "Levin",
  "Levy", "Lieberman", "Lifshitz", "Lior", "Lipschitz", "Lobel", "Lustig", "Magen", "Maimon", "Malchi",
  "Malka", "Malkin", "Manor", "Maoz", "Marom", "Mass", "Matz", "Mayer", "Medina", "Meir",
  "Melamed", "Mendel", "Meshulam", "Mizrahi", "Mor", "Mordechai", "Moshe", "Nagar", "Nahmani", "Naim",
  "Namir", "Natan", "Navon", "Neeman", "Negev", "Nir", "Nissan", "Noam", "Noy", "Ohana",
  "Ophir", "Oren", "Orlev", "Ovadia", "Paz", "Peled", "Peres", "Peretz", "Perez", "Porat",
  "Rabin", "Rabinowitz", "Rahamim", "Ram", "Ravid", "Raz", "Regev", "Reich", "Reuveni", "Rimon",
  "Ronen", "Rosen", "Rosenberg", "Rosenblum", "Roth", "Rubin", "Sabag", "Sadan", "Sagi", "Salem",
  "Salomon", "Samocha", "Sasson", "Schwartz", "Segal", "Shachar", "Shaked", "Shalom", "Shamir", "Shapira",
  "Sharon", "Shechter", "Shemesh", "Shenhav", "Shilo", "Shimon", "Shmuel", "Shoham", "Shpigel", "Shtark",
  "Sidi", "Silver", "Siman Tov", "Sinai", "Sofer", "Sokol", "Stern", "Suissa", "Swisa", "Tadmor",
  "Tal", "Tamir", "Tayar", "Tevet", "Toledano", "Tzafir", "Tzur", "Vaknin", "Vardi", "Wagner",
  "Weiss", "Wolf", "Yadin", "Yahav", "Yarkoni", "Yechezkel", "Yehoshua", "Yehuda", "Yishai", "Yitzhaki",
  "Yosef", "Zadok", "Zamir", "Zohar", "Zuckerman"
];