export const KAZAKH_MALE_FIRSTNAMES = [
  "Aidar", "Aidos", "Aisultan", "Alikhan", "Alim", "Almas", "Almat", "Aman", "Amanat", "Amir",
  "Anuar", "Arlan", "Arman", "Arsen", "Arystan", "Asan", "Asat", "Askar", "Aslan", "Asset",
  "Ayan", "Azamat", "Azat", "Bakhyt", "Bakir", "Bakyt", "Bauyrzhan", "Bek", "Bekzat", "Berik",
  "Bolat", "Daniyar", "Daulet", "Dauren", "Dauyr", "Dias", "Dilmukhamed", "Dmitriy", "Dosym", "Edil",
  "Eldar", "Eldos", "Erbol", "Erbolat", "Erden", "Erdos", "Erlan", "Ermek", "Ermurat", "Ernar",
  "Ernur", "Ersultan", "Galym", "Galymzhan", "Gani", "Gulmurat", "Ilyas", "Islam", "Ismail", "Iskander",
  "Kairat", "Kaisar", "Kaldybek", "Kanat", "Karamat", "Kasym", "Kenes", "Kenzhebek", "Kuanysh", "Kuat",
  "Madi", "Madiyar", "Maksat", "Mansur", "Marat", "Margulan", "Miras", "Mirlan", "Murat", "Musa",
  "Nartay", "Nazar", "Nurlan", "Nursultan", "Nurtas", "Nurzhan", "Olzhas", "Omar", "Rakhat", "Ramazan",
  "Rasul", "Rauan", "Rinat", "Rishat", "Rustam", "Sadyk", "Sagynysh", "Saken", "Sanzhar", "Sapar",
  "Sardar", "Sarsen", "Sartay", "Serik", "Serikbay", "Serikzhan", "Shakhzod", "Shamil", "Shyngys", "Sultan",
  "Syrgak", "Tair", "Talgar", "Talip", "Tamerlan", "Taras", "Temir", "Temirlan", "Tengiz", "Timur",
  "Tolegen", "Toleu", "Tomas", "Tursyn", "Ulan", "Umar", "Yerbol", "Yerkebulan", "Yermek", "Yermurat",
  "Yernar", "Yernur", "Yersultan", "Yerzhan", "Yessen", "Yusup", "Zhanat", "Zhandos", "Zhanibek", "Zhanuzak",
  "Zhaslan", "Zhasulan", "Zhasur", "Zhassulan", "Zhasyr", "Zhetpis", "Zhomart", "Zhumas", "Zhyrgal", "Ziyad",
  "Abay", "Abzal", "Adil", "Adilet", "Adilzhan", "Aidos", "Akhmet", "Akmaral", "Aktan", "Alen",
  "Ali", "Alibek", "Alik", "Alisher", "Almas", "Altyn", "Amangeldy", "Amirzhan", "Anuarbek", "Ardak",
  "Arman", "Arsen", "Artyom", "Asanali", "Asel", "Askhat", "Aslanbek", "Aybek", "Aydar", "Ayman",
  "Aysultan", "Azamat", "Azat", "Bakhytzhan", "Bakir", "Baktybek", "Bauyrzhan", "Bekbolat", "Beknur", "Bekzat",
  "Berik", "Bolatbek", "Daniil", "Daniyar", "Darkhan", "Dauletbek", "Dauren", "Dauyrzhan", "Dias", "Dilmurat",
  "Dmitry", "Dos", "Duman", "Edige", "Eldar", "Elkhan", "Elman", "Elnur", "Eraly", "Erbolat",
  "Erdaulet", "Erden", "Erdos", "Erlan", "Ermek", "Ermurat", "Ernar", "Ernur", "Ersain", "Ersultan",
  "Erzhan", "Galym", "Gani", "Ibragim", "Ilias", "Ilyas", "Islam", "Ismail", "Kairat", "Kaisar",
  "Kanat", "Karamat", "Kasym", "Kenes", "Kenzhe", "Kuanysh", "Kuat", "Madi", "Madiyar", "Maksat",
  "Marat", "Margulan", "Miras", "Mirlan", "Murat", "Musa", "Nartay", "Nazar", "Nurlan", "Nursultan",
  "Nurtas", "Nurzhan", "Olzhas", "Omar", "Rakhat", "Ramazan", "Rasul", "Rauan", "Rinat", "Rishat",
  "Rustam", "Sagynysh", "Saken", "Sanzhar", "Sapar", "Sardar", "Serik", "Serikzhan", "Shakhzod", "Shamil",
  "Shyngys", "Sultan", "Syrgak", "Tair", "Talgar", "Talip", "Tamerlan", "Temir", "Temirlan", "Tengiz",
  "Timur", "Tolegen", "Tursyn", "Ulan", "Umar", "Yerbol", "Yerkebulan", "Yermek", "Yermurat", "Yernar",
  "Yernur", "Yersultan", "Yerzhan", "Yessen", "Yusup", "Zhanat", "Zhandos", "Zhanibek", "Zhaslan", "Zhasulan",
  "Zhasur", "Zhassulan", "Zhyrgal", "Ziyad"
];

export const KAZAKH_MALE_LASTNAMES = [
  "Abdrakhmanov", "Abilov", "Akhmetov", "Akhmetzhanov", "Aliev", "Alimbekov", "Alimzhanov", "Altynbekov", "Amanov", "Amanzholov",
  "Amirbekov", "Amirkhanov", "Artykbayev", "Asanov", "Askarov", "Aslanov", "Aubakirov", "Auezov", "Auyezov", "Baimbetov",
  "Baimenov", "Baitursynov", "Baktybayev", "Balapanov", "Balgimbayev", "Balmagambetov", "Balmukhanov", "Baltabayev", "Batyrov", "Bauyrzhanov",
  "Bekbolatov", "Bekmuratov", "Bekov", "Bekzhanov", "Berdibekov", "Berdikulov", "Berdybekov", "Biyashev", "Bolatov", "Boranbayev",
  "Bozhbanov", "Burkitbayev", "Daulenov", "Dauletov", "Dauletbayev", "Dauletbekov", "Dauletov", "Doszhanov", "Duisenov", "Dusenov",
  "Elemesov", "Ermekov", "Ermolov", "Erzhanov", "Esengeldiyev", "Esenov", "Esirkepov", "Gabdullin", "Galiyev", "Gulimov",
  "Ibraev", "Ibragimov", "Ibrayev", "Ilyasov", "Imashev", "Isayev", "Iskakov", "Iskanderov", "Ismagulov", "Ismailov",
  "Jabayev", "Jaksybekov", "Jandarbekov", "Jangeldin", "Japarov", "Jumabaev", "Kabylbekov", "Kairatov", "Kairbekov", "Kaliev",
  "Kalmakhanov", "Kalmuratov", "Kamalov", "Kambarov", "Kambarov", "Kanagatov", "Kanatov", "Karashev", "Karimov", "Kasymov",
  "Kassymov", "Kenzhebayev", "Kenzhebekov", "Kenzhegulov", "Khamitov", "Khairullin", "Khasenov", "Khasenuly", "Khatimov", "Khozhamzharov",
  "Kozhakhmetov", "Kozhamkulov", "Kudaibergenov", "Kudaibergenuly", "Kulanov", "Kulmanov", "Kurmangaliyev", "Kusainov", "Kussainov", "Kydyrmanov",
  "Madenov", "Madiyev", "Maksutov", "Mamytov", "Maratov", "Mashrapov", "Mataev", "Matayev", "Mukhtarov", "Mukushev",
  "Muratov", "Mussin", "Mussinov", "Myrzabayev", "Myrzakhmetov", "Nabiyev", "Nurgaliyev", "Nurgazin", "Nurkasymov", "Nurkenov",
  "Nurlanov", "Nurlybayev", "Nurmoldin", "Nurmukhamedov", "Nurpeisov", "Nursultanov", "Nurymov", "Nusupov", "Omarov", "Orazbayev",
  "Orazov", "Orynbayev", "Orynbekov", "Ospanov", "Ospanuly", "Otegenov", "Otepbergenov", "Oteuliyev", "Otkeldiyev", "Otynshiyev",
  "Pavlov", "Rakhimov", "Rakhmanov", "Rakhmetov", "Ramazanov", "Ryskulov", "Sabirov", "Sadykov", "Sagimbayev", "Sagindykov",
  "Sakenov", "Salgaraev", "Salmaganbetov", "Salykov", "Samatov", "Saparov", "Sarbayev", "Sarsenbayev", "Sarsenov", "Sarybayev",
  "Satpayev", "Sautov", "Serikbayev", "Serikov", "Shaikenov", "Shaimardanov", "Shakenov", "Shalabayev", "Shamshiyev", "Sharipov",
  "Shayakhmetov", "Shaydullin", "Shaymerdenov", "Shegenov", "Shukurov", "Smailov", "Smagulov", "Smanov", "Smaylov", "Sultanov",
  "Sydykov", "Taimasov", "Tazhibayev", "Tazhiyev", "Temirbekov", "Temirgaliev", "Tleubayev", "Tleugabylov", "Tleulessov", "Tolegenov",
  "Toleuov", "Toleubayev", "Tulegenov", "Tulepov", "Tuleubayev", "Tursunov", "Ualiyev", "Ulanov", "Umarov", "Urazbayev",
  "Urazov", "Utegenov", "Uteuliyev", "Uzbekov", "Yakubov", "Yerzhanov", "Yessimov", "Yessengeldiyev", "Yessimov", "Yusupov",
  "Zhanabayev", "Zhanatov", "Zhandarbekov", "Zhanibekov", "Zhanuzakov", "Zhasuzakov", "Zhaylauov", "Zholdasov", "Zholdybayev", "Zhumashev",
  "Zhussupov", "Zhunisov", "Zhunusov", "Ziyabekov", "Zhumagaliyev", "Zhumabayev", "Zhumagulov", "Zhumaliev", "Zhumartov", "Zhumatov"
];