export const OCEANIAN_MALE_FIRSTNAMES = [
  'Oliver', 'Noah', 'Jack', 'William', 'Leo', 'Lucas', 'Henry', 'Charlie', 'Thomas', 'James',
  'Liam', 'Alexander', 'Harrison', 'Ethan', 'Mason', 'Lachlan', 'Hunter', 'Arlo', 'Hugo', 'Cooper',
  'Oscar', 'Elijah', 'Hudson', 'Archie', 'Levi', 'Luca', 'Theodore', 'Benjamin', 'Samuel', 'Daniel',
  'Matthew', 'Michael', 'David', 'Joseph', 'John', 'Robert', 'George', 'Arthur', 'Ryan', 'Jacob',
  'Joshua', 'Luke', 'Isaac', 'Sebastian', 'Xavier', 'Kai', 'Malakai', 'Koa', 'Manaia', 'Ariki',
  'Te Ariki', 'Sione', 'Tevita', 'Viliami', 'Paula', 'Etuate', 'Keanu', 'Tai', 'Kainoa', 'Lani',
  'Moana', 'Tane', 'Wiremu', 'Anaru', 'Nikau', 'Aroha', 'Mana', 'Rangi', 'Tama', 'Atamai',
  'Kelekolio', 'Malachi', 'Jone', 'Mohammed', 'John', 'Peter', 'Thomas', 'James', 'Michael',
  'David', 'Joseph', 'Matthew', 'Andrew', 'Mark', 'Luke', 'Paul', 'Steven', 'Daniel', 'Christopher',
  'Joshua', 'Ryan', 'Ethan', 'Jacob', 'Samuel', 'Benjamin', 'William', 'Henry', 'Jack', 'Oliver',
  'Noah', 'Leo', 'Lucas', 'Charlie', 'Thomas', 'James', 'Liam', 'Alexander', 'Harrison', 'Mason',
  'Lachlan', 'Hunter', 'Arlo', 'Hugo', 'Cooper', 'Oscar', 'Elijah', 'Hudson', 'Archie', 'Levi',
  'Luca', 'Theodore', 'Benjamin', 'Samuel', 'Daniel', 'Matthew', 'Michael', 'David', 'Joseph',
  'John', 'Robert', 'George', 'Arthur', 'Ryan', 'Jacob', 'Joshua', 'Luke', 'Isaac', 'Sebastian',
  'Xavier', 'Kai', 'Malakai', 'Koa', 'Manaia', 'Ariki', 'Te Ariki', 'Sione', 'Tevita', 'Viliami',
  'Paula', 'Etuate', 'Keanu', 'Tai', 'Kainoa', 'Lani', 'Tane', 'Wiremu', 'Anaru', 'Nikau',
  'Rangi', 'Tama', 'Atamai', 'Kelekolio', 'Jone', 'Peter', 'Thomas', 'James', 'Michael', 'David',
  'Joseph', 'Matthew', 'Andrew', 'Mark', 'Luke', 'Paul', 'Steven', 'Daniel', 'Christopher', 'Joshua',
  'Ryan', 'Ethan', 'Jacob', 'Samuel', 'Benjamin', 'William', 'Henry', 'Jack', 'Oliver', 'Noah',
  'Leo', 'Lucas', 'Charlie', 'Thomas', 'James', 'Liam', 'Alexander', 'Harrison', 'Mason', 'Lachlan',
  'Hunter', 'Arlo', 'Hugo', 'Cooper', 'Oscar', 'Elijah', 'Hudson', 'Archie', 'Levi', 'Luca',
  'Theodore', 'Benjamin', 'Samuel', 'Daniel', 'Matthew', 'Michael', 'David', 'Joseph', 'John',
  'Robert', 'George', 'Arthur', 'Ryan', 'Jacob', 'Joshua', 'Luke', 'Isaac', 'Sebastian', 'Xavier',
  'Kai', 'Malakai', 'Koa', 'Manaia', 'Ariki', 'Te Ariki', 'Sione', 'Tevita', 'Viliami', 'Paula',
  'Etuate', 'Keanu', 'Tai', 'Kainoa', 'Tane', 'Wiremu', 'Anaru', 'Nikau', 'Rangi', 'Tama',
  'Atamai', 'Kelekolio', 'Mana', 'Moana', 'Aroha', 'Ranginui', 'Kiwa', 'Kawe', 'Te Koha', 'Taniora',
  'Manuka', 'Ahi', 'Ari', 'Matiu', 'Wiremu', 'Hemi', 'Tama', 'Kahu', 'Rua', 'Tahu',
  'Teina', 'Whaka', 'Mikaere', 'Rawiri', 'Hirini', 'Hohepa', 'Rewi', 'Tawhiri', 'Kereama', 'Maui',
  'Kupe', 'Tonga', 'Samoa', 'Fiji', 'Vanuatu', 'Solomon', 'Brandon', 'Caleb', 'Eddie', 'Rex',
  'Clinton', 'Ryan', 'Daniel', 'Michael', 'David', 'John', 'Shaun', 'Bobby', 'Fabian', 'Arnold',
  'Nelson', 'Jesse', 'Danny', 'Spencer', 'Damien', 'Jackson', 'Mike', 'Patrick', 'Samson', 'Elvis',
  'Perry', 'Nigel', 'Marc', 'Ben', 'Greydon', 'Nollen', 'Iven', 'Oko', 'Silkarni', 'Paka'
];

export const OCEANIAN_MALE_LASTNAMES = [
  'Smith', 'Jones', 'Williams', 'Brown', 'Wilson', 'Taylor', 'Johnson', 'White', 'Martin', 'Anderson',
  'Thompson', 'Jackson', 'Harris', 'Thomas', 'Clark', 'Lewis', 'Robinson', 'Walker', 'Young', 'Allen',
  'King', 'Wright', 'Scott', 'Green', 'Baker', 'Adams', 'Nelson', 'Hill', 'Campbell', 'Mitchell',
  'Roberts', 'Carter', 'Phillips', 'Evans', 'Turner', 'Collins', 'Edwards', 'Stewart', 'Morris', 'Murphy',
  'Cook', 'Rogers', 'Morgan', 'Peterson', 'Cooper', 'Reed', 'Bailey', 'Bell', 'Kelly', 'Howard',
  'Ward', 'Cox', 'Richardson', 'Watson', 'Brooks', 'Wood', 'James', 'Bennett', 'Gray', 'Hughes',
  'Price', 'Foster', 'Sanders', 'Ross', 'Powell', 'Long', 'Perry', 'Russell', 'Henderson', 'Coleman',
  'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons',
  'Foster', 'Gonzalez', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes', 'Myers', 'Ford',
  'Hamilton', 'Graham', 'Sullivan', 'Wallace', 'Woods', 'Cole', 'West', 'Jordan', 'Owens', 'Reynolds',
  'Fisher', 'Ellis', 'Harrison', 'Gibson', 'Mcdonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray',
  'Freeman', 'Wells', 'Webb', 'Simpson', 'Stevens', 'Tucker', 'Porter', 'Hunter', 'Hicks', 'Crawford',
  'Henry', 'Boyd', 'Mason', 'Morales', 'Kennedy', 'Warren', 'Dixon', 'Ramos', 'Reyes', 'Burns',
  'Gordon', 'Shaw', 'Holmes', 'Rice', 'Robertson', 'Hunt', 'Black', 'Daniels', 'Palmer', 'Mills',
  'Nichols', 'Grant', 'Knight', 'Ferguson', 'Rose', 'Stone', 'Hawkins', 'Dunn', 'Perkins', 'Hudson',
  'Spencer', 'Gardner', 'Stephens', 'Payne', 'Pierce', 'Berry', 'Matthews', 'Arnold', 'Wagner', 'Willis',
  'Ray', 'Watkins', 'Olson', 'Carroll', 'Duncan', 'Snyder', 'Hart', 'Cunningham', 'Bradley', 'Lane',
  'Andrews', 'Ruiz', 'Harper', 'Fox', 'Riley', 'Armstrong', 'Carpenter', 'Weaver', 'Greene', 'Lawrence',
  'Elliott', 'Chavez', 'Sims', 'Austin', 'Peters', 'Kelley', 'Franklin', 'Lawson', 'Fields', 'Gutierrez',
  'Ryan', 'Schmidt', 'Carr', 'Vasquez', 'Castillo', 'Wheeler', 'Chapman', 'Oliver', 'Montgomery', 'Richards',
  'Williamson', 'Johnston', 'Banks', 'Meyer', 'Bishop', 'Mccoy', 'Howell', 'Alvarez', 'Morrison', 'Hansen',
  'Fernandez', 'Garza', 'Harvey', 'Little', 'Burton', 'Stanley', 'Nguyen', 'George', 'Jacobs', 'Reid',
  'Kim', 'Fuller', 'Lynch', 'Dean', 'Gilbert', 'Garrett', 'Romero', 'Welch', 'Larson', 'Frazier',
  'Burke', 'Hanson', 'Day', 'Mendoza', 'Moreno', 'Bowman', 'Medina', 'Fowler', 'Brewer', 'Hoffman',
  'Carlson', 'Silva', 'Pearson', 'Holland', 'Douglas', 'Fleming', 'Jensen', 'Vargas', 'Byrd', 'Davidson',
  'Hopkins', 'May', 'Terrell', 'Terry', 'Herrera', 'Wade', 'Soto', 'Walters', 'Curtis', 'Neal',
  'Caldwell', 'Lowe', 'Jennings', 'Barnett', 'Graves', 'Jimenez', 'Horton', 'Shelton', 'Barrett', 'Obrien',
  'Castro', 'Sutton', 'Gregory', 'Mckinney', 'Lucas', 'Miles', 'Craig', 'Rodriquez', 'Chambers', 'Holt',
  'Lambert', 'Fletcher', 'Watts', 'Bates', 'Hale', 'Rhodes', 'Pena', 'Beck', 'Newman', 'Haynes',
  'McDaniel', 'Mendez', 'Bush', 'Vaughn', 'Parks', 'Dawson', 'Santiago', 'Norris', 'Hardy', 'Love',
  'Steele', 'Curry', 'Powers', 'Schultz', 'Barker', 'Guzman', 'Page', 'Munoz', 'Ball', 'Keller',
  'Chandler', 'Weber', 'Leonard', 'Walsh', 'Lyons', 'Ramsey', 'Wolfe', 'Schneider', 'Mullins', 'Benson',
  'Sharp', 'Bowen', 'Daniel', 'Barber', 'Cummings', 'Hines', 'Baldwin', 'Griffith', 'Valdez', 'Hubbard',
  'Salazar', 'Reeves', 'Warner', 'Stevenson', 'Burgess', 'Santos', 'Tate', 'Cross', 'Garner', 'Mann',
  'Mack', 'Moss', 'Thornton', 'Dennis', 'Mcgee', 'Farmer', 'Delacruz', 'Little', 'Walton', 'Bates',
  'John', 'Peter', 'Thomas', 'James', 'Paul', 'Mark', 'Luke', 'Matthew', 'Andrew', 'Joseph',
  'David', 'Michael', 'Steven', 'Christopher', 'Daniel', 'Joshua', 'Ryan', 'Jacob', 'Nicholas', 'Tyler',
  'Brandon', 'Austin', 'Benjamin', 'Samuel', 'Nathan', 'Logan', 'Christian', 'Jonathan', 'Caleb', 'Dylan',
  'Isaac', 'Gavin', 'Jackson', 'Eli', 'Jordan', 'Hunter', 'Luke', 'Angel', 'Kevin', 'Jack',
  'Cody', 'Asher', 'Cameron', 'Chase', 'Cooper', 'Xavier', 'Parker', 'Jace', 'Miles', 'Blake',
  'Aiden', 'Leo', 'Theo', 'Kai', 'Malakai', 'Koa', 'Manaia', 'Ariki', 'Te Ariki', 'Sione',
  'Tevita', 'Viliami', 'Paula', 'Etuate', 'Keanu', 'Tai', 'Kainoa', 'Tane', 'Wiremu', 'Anaru',
  'Nikau', 'Rangi', 'Tama', 'Atamai', 'Kelekolio', 'Aiono', 'Faamausili', 'Fatialofa', 'Fepuleai', 'Fuamatu',
  'Laulala', 'Lealamanua', 'Nuuausala', 'Palamo', 'Palepoi', 'Salavea', 'Savea', 'Vaai', 'Tuilaepa', 'Ah Mu',
  'Alofaituli', 'Faleafa', 'Gatoloai', 'Singh', 'Kaur', 'Patel', 'Kumar', 'Sharma', 'Wong', 'Lee',
  'Chen', 'Zhang', 'Liu', 'Li', 'Wang', 'Yang', 'Maori', 'Tawhiri', 'Te Hira', 'Mabo',
  'Fatnowna', 'Lui', 'Mose', 'Solomon', 'Tonga', 'Saukuru', 'Quakawoot', 'Mussing', 'Minniecon', 'Budby'
];