export const OTHER_ASIAN_MALE_FIRSTNAMES = [
  "Minh", "Anh", "Huy", "Long", "Nam", "Tuấn", "Hùng", "Quang", "Bảo", "Đức",
  "Thành", "Phúc", "Việt", "Hoàng", "Khánh", "Dương", "Hải", "Sơn", "Trung", "Kiên",
  "Tùng", "Linh", "Ngọc", "Vinh", "Thắng", "Cường", "Đạt", "Phát", "Tiến", "An",
  "Somchai", "Arthit", "Chaiwat", "Thanakorn", "Pongsakorn", "Kittipong", "Nattapong",
  "Sarawut", "Anurak", "Apichai", "Boonchai", "Chatchai", "Dusit", "Ekkachai", "Kritsada",
  "Prawit", "Sompong", "Surachai", "Thawatchai", "Wichai", "Prem", "Chai", "Arun",
  "Muhammad", "Ahmad", "Agus", "Budi", "Joko", "Sutrisno", "Slamet", "Mulyadi", "Herman",
  "Supardi", "Wahyudi", "Aditya", "Bagus", "Bayu", "Dimas", "Eko", "Fajar", "Gede",
  "Hendra", "Iwan", "Rizky", "Arief", "Bintang", "Dharma", "Guntur", "Haris", "Indra",
  "Jacob", "Nathaniel", "Gabriel", "Joshua", "James", "Daniel", "Angelo", "Christian",
  "John", "Mark", "Matthew", "Michael", "Rafael", "Ryan", "Zack", "Alden", "Andres",
  "Carlos", "Darius", "Ezekiel", "Felix", "Moises", "Nathan", "Prince", "Ethan",
  "Aiden", "Liam", "Lucas", "Isaac", "Evan", "Wayne", "Theo", "Shane", "Aaron",
  "Minh", "Anh", "Huy", "Long", "Nam", "Tuấn", "Hùng", "Quang", "Bảo", "Đức",
  "Somchai", "Arthit", "Chaiwat", "Thanakorn", "Pongsakorn", "Kittipong", "Nattapong",
  "Muhammad", "Ahmad", "Agus", "Budi", "Joko", "Sutrisno", "Slamet", "Mulyadi",
  "Jacob", "Gabriel", "Joshua", "James", "Daniel", "Angelo", "Christian", "John",
  "Mark", "Matthew", "Michael", "Rafael", "Ryan", "Ethan", "Aiden", "Liam",
  "Lucas", "Isaac", "Evan", "Wayne", "Theo", "Aditya", "Bayu", "Dimas", "Rizky",
  "Arief", "Hendra", "Bagus", "Eko", "Fajar", "Gede", "Haris", "Indra", "Bintang",
  "Anurak", "Apichai", "Chatchai", "Kritsada", "Sompong", "Wichai", "Prem", "Arun",
  "Tuấn", "Hùng", "Minh", "Anh", "Huy", "Long", "Nam", "Quang", "Bảo", "Đức",
  "Thành", "Phúc", "Việt", "Hoàng", "Khánh", "Dương", "Hải", "Sơn", "Trung", "Kiên",
  "Tùng", "Linh", "Ngọc", "Vinh", "Thắng", "Cường", "Đạt", "Phát", "Tiến", "An",
  "Somchai", "Arthit", "Chaiwat", "Thanakorn", "Pongsakorn", "Kittipong", "Nattapong",
  "Sarawut", "Anurak", "Apichai", "Boonchai", "Chatchai", "Dusit", "Ekkachai", "Kritsada",
  "Prawit", "Sompong", "Surachai", "Thawatchai", "Wichai", "Prem", "Chai", "Arun",
  "Muhammad", "Ahmad", "Agus", "Budi", "Joko", "Sutrisno", "Slamet", "Mulyadi", "Herman",
  "Supardi", "Wahyudi", "Aditya", "Bagus", "Bayu", "Dimas", "Eko", "Fajar", "Gede",
  "Hendra", "Iwan", "Rizky", "Arief", "Bintang", "Dharma", "Guntur", "Haris", "Indra",
  "Jacob", "Nathaniel", "Gabriel", "Joshua", "James", "Daniel", "Angelo", "Christian",
  "John", "Mark", "Matthew", "Michael", "Rafael", "Ryan", "Zack", "Alden", "Andres",
  "Carlos", "Darius", "Ezekiel", "Felix", "Moises", "Nathan", "Prince", "Ethan",
  "Aiden", "Liam", "Lucas", "Isaac", "Evan", "Wayne", "Theo", "Shane", "Aaron"
];

export const OTHER_ASIAN_SURNAMES = [
  "Nguyen", "Tran", "Le", "Pham", "Hoang", "Huynh", "Phan", "Vu", "Vo", "Dang",
  "Bui", "Do", "Ho", "Ngo", "Duong", "Ly", "Truong", "Dinh", "Hua", "Cao",
  "Saetang", "Suwannathat", "Chaiyaporn", "Sombat", "Thepnakorn", "Bunjong", "Chanthara",
  "Charoensuk", "Kittipong", "Pongsakorn", "Sompong", "Thawatchai", "Wichai", "Anurak",
  "Santoso", "Wijaya", "Saputra", "Pratama", "Susanto", "Hidayat", "Nugroho", "Setiawan",
  "Rahman", "Abdullah", "Siregar", "Simanjuntak", "Pangestu", "Gunawan", "Santos",
  "Dela Cruz", "Garcia", "Reyes", "Cruz", "Bautista", "Lopez", "Gonzales", "Aquino",
  "Ramos", "Torres", "Rivera", "Mercado", "Morales", "Santiago", "Fernandez", "Santos",
  "Tan", "Chan", "Chong", "Lim", "Lee", "Wong", "Lin", "Huang", "Chang", "Wu",
  "Liu", "Yang", "Goh", "Ong", "Teo", "Ang", "Koh", "Liew", "Chew", "Chia",
  "Tay", "Seah", "Yeo", "Neo", "Lau", "Chin", "Fong", "Sim", "Kwan", "Cheong",
  "Nguyen", "Tran", "Le", "Pham", "Hoang", "Huynh", "Phan", "Vu", "Vo", "Dang",
  "Bui", "Do", "Ho", "Ngo", "Duong", "Ly", "Truong", "Dinh", "Hua", "Cao",
  "Saetang", "Suwannathat", "Chaiyaporn", "Sombat", "Thepnakorn", "Bunjong", "Chanthara",
  "Charoensuk", "Kittipong", "Pongsakorn", "Sompong", "Thawatchai", "Wichai", "Anurak",
  "Santoso", "Wijaya", "Saputra", "Pratama", "Susanto", "Hidayat", "Nugroho", "Setiawan",
  "Rahman", "Abdullah", "Siregar", "Simanjuntak", "Pangestu", "Gunawan", "Santos",
  "Dela Cruz", "Garcia", "Reyes", "Cruz", "Bautista", "Lopez", "Gonzales", "Aquino",
  "Ramos", "Torres", "Rivera", "Mercado", "Morales", "Santiago", "Fernandez", "Santos",
  "Tan", "Chan", "Chong", "Lim", "Lee", "Wong", "Lin", "Huang", "Chang", "Wu",
  "Liu", "Yang", "Goh", "Ong", "Teo", "Ang", "Koh", "Liew", "Chew", "Chia",
  "Tay", "Seah", "Yeo", "Neo", "Lau", "Chin", "Fong", "Sim", "Kwan", "Cheong",
  "Nguyen", "Tran", "Le", "Pham", "Hoang", "Huynh", "Phan", "Vu", "Vo", "Dang",
  "Bui", "Do", "Ho", "Ngo", "Duong", "Ly", "Truong", "Dinh", "Hua", "Cao",
  "Saetang", "Suwannathat", "Chaiyaporn", "Sombat", "Thepnakorn", "Bunjong", "Chanthara",
  "Charoensuk", "Kittipong", "Pongsakorn", "Sompong", "Thawatchai", "Wichai", "Anurak",
  "Santoso", "Wijaya", "Saputra", "Pratama", "Susanto", "Hidayat", "Nugroho", "Setiawan",
  "Rahman", "Abdullah", "Siregar", "Simanjuntak", "Pangestu", "Gunawan", "Santos",
  "Dela Cruz", "Garcia", "Reyes", "Cruz", "Bautista", "Lopez", "Gonzales", "Aquino",
  "Ramos", "Torres", "Rivera", "Mercado", "Morales", "Santiago", "Fernandez", "Santos",
  "Tan", "Chan", "Chong", "Lim", "Lee", "Wong", "Lin", "Huang", "Chang", "Wu",
  "Liu", "Yang", "Goh", "Ong", "Teo", "Ang", "Koh", "Liew", "Chew", "Chia",
  "Tay", "Seah", "Yeo", "Neo", "Lau", "Chin", "Fong", "Sim", "Kwan", "Cheong"
];

